name: Deploy
on: [push]

jobs:
  deploy:
    permissions:
      contents: read
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global init.defaultBranch main
      - uses: actions/checkout@v3
        with:
          repository: cysec-lab/ryusei_private
          token: ${{ secrets.ORG_GITHUB_PAT }}
          path: src
          ref: 'main'
      - run: |
          pwd
          ls -la
          ls -la src
