name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cysec-lab/ryusei_private
          token: ${{ secrets.ORG_GITHUB_PAT }}
          path: .
          ref: 'main'
      - run: |
          pwd
          ls -la
          ls -la src
